# More info https://github.com/dotnet/dotnet-docker/tree/master/samples
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS="https://*:443;http://*:80"
EXPOSE 80
EXPOSE 443

COPY ["MongoDataAccess.API.csproj", "app/"]

RUN dotnet restore app/MongoDataAccess.API.csproj

COPY . /app
WORKDIR /app
RUN dotnet build --no-restore -c $BUILD_CONFIGURATION

RUN dotnet publish -c $BUILD_CONFIGURATION --output ../publish

WORKDIR /publish
ENTRYPOINT ["dotnet", "MongoDataAccess.API.dll"]