version: '3.4'

services:
  mongo.db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: krlosmederos
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27019:27017

  mongodataaccess.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on: 
      - mongo.db